server:
  port: 8888 # config server port
  
spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/inlineno1/spring-cloud-config-repo # config files location (git uri) / private 환경으로 변경 필요